from __future__ import annotations

from models.contracts import BasePlannerEngine, PlannerItem, PlannerPreview, TemplateSuggestion


class PlannerEngine(BasePlannerEngine):
    async def preview(self, kind: str, objective: str, context: dict | None = None) -> PlannerPreview:
        context = context or {}
        if kind == "recipe":
            pantry = context.get("pantry", [])
            return PlannerPreview(
                kind=kind,
                title="Recipe Draft",
                summary=f"A quick recipe plan for: {objective}",
                items=[
                    PlannerItem(title="Prep ingredients", notes=", ".join(pantry) or "Use available pantry items"),
                    PlannerItem(title="Cook main dish", notes=f"Focus on {objective} flavors", time_slot="20 min"),
                    PlannerItem(title="Plate and garnish", notes="Serve warm"),
                ],
                recipe={
                    "ingredients": pantry or ["olive oil", "salt", "pepper"],
                    "steps": ["Prep ingredients", "Cook in pan", "Serve and garnish"],
                },
            )
        if kind == "template":
            return PlannerPreview(
                kind=kind,
                title="Friendly Message Templates",
                summary=f"Drafts for: {objective}",
                templates=[
                    TemplateSuggestion(title="Warm Greeting", tone="friendly", content=f"Hey! Just checking in about {objective}. Hope you're doing great."),
                    TemplateSuggestion(title="Professional Note", tone="professional", content=f"Hello, I wanted to follow up regarding {objective}. Let me know what works best."),
                ],
            )
        lines = [line.strip() for line in objective.split(",") if line.strip()]
        items = [
            PlannerItem(
                title=line,
                notes=f"{kind.title()} task generated by JARVIS",
                time_slot=f"{9 + index}:00",
            )
            for index, line in enumerate(lines or [objective])
        ]
        return PlannerPreview(
            kind=kind,
            title=f"{kind.title()} Preview",
            summary=f"Generated {len(items)} items for {objective}.",
            items=items,
        )

